<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'stringEncode' => array($vendorDir . '/paquettg/string-encode/src'),
    'SimpleSoftwareIO\\QrCode\\' => array($vendorDir . '/simplesoftwareio/simple-qrcode/src'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'KubAT\\PhpSimple\\HtmlDomParser' => array($vendorDir . '/kub-at/php-simple-html-dom-parser/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'BaconQrCode' => array($vendorDir . '/bacon/bacon-qr-code/src'),
);
